<?php

namespace Tests\Unit;

use App\Actions\CreateUserAction;
use App\Actions\RegisterUserAction;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Tests\TestCase;

class CreateUserActionTest extends TestCase
{
    private CreateUserAction $action;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->action = new CreateUserAction();
    }

    /**
     * A basic unit test example.
     *
     * @return Model|User
     */
    public function testRegisterUserAction(): User|Model
    {
        $userName = 'Daniil Boyko';

        $response = $this->action->handle();
        $this->assertEquals($userName, $response->name);

        return $response;
    }

    public function testModelExists()
    {
        $this->assertModelExists($this->testRegisterUserAction());
    }
}
