<?php

namespace Tests\Unit;

use App\Actions\CreatePostAction;
use Tests\TestCase;

class CreatePostActionTest extends TestCase
{
    private CreatePostAction $action;

    public function setUp(): void
    {
//        second variant
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->action = new CreatePostAction();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testHandle(): void
    {
//        the first variant
//        $action = new CreatePostAction();
//        $result = $action->handle();
        $response = $this->action->handle();
        $this->assertEquals('Test creating title', $response->title);
    }
}
