<?php

namespace Tests\Unit;

use App\Actions\TransformUsersAction;
use App\Models\User;
use Tests\TestCase;

class TransformUsersTest extends TestCase
{
    private TransformUsersAction $action;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->action = new TransformUsersAction();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testTransformUsersAction(): void
    {
        $users = User::factory(3)->make();
        $result = $this->action->handle($users);
        $expectedFormattedTime = now()->format('Y.m.d');
        $this->assertEquals($expectedFormattedTime, $result->increased_at);
    }
}
