<?php

namespace Tests\Unit;

use App\Actions\UpdateUserAction;
use Tests\TestCase;

class UpdateUserActionTest extends TestCase
{
    private UpdateUserAction $action;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->action = new UpdateUserAction();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testUpdateUserAction(): void
    {
        $data = [
            'id' => 3,
            'field' => 'name',
            'newValue' => 'New Name',
        ];

        $response = $this->action->handle($data);

        $this->assertTrue($response);
    }
}
